# Local-only override: do not change base compose used for prod/CI
# Frontends are optional via the `frontend` profile; core services always run.

services:
  webapp:
    profiles: ["frontend"]

  siteapp:
    profiles: ["frontend"]

  apiapp:
    build:
      context: .
      dockerfile: apiapp/Dockerfile
    ports:
      - "${APIAPP_HTTP_PORT:-18080}:8000"

  keycloak:
    build:
      context: ./keycloak

  mkdocs:
    build:
      context: ./mkdocs
