services:

  # Fastapi backend
  apiapp:
    image: ${DOCKER_REGISTRY}/${APP_ENV:-app}_apiapp:latest
    container_name: ${APP_ENV:-app}_apiapp
    hostname: ${APP_ENV:-app}_apiapp
    restart: unless-stopped
    #TODO: remove, it's not necessary and not good idea for prod
    #ports:
    #  - ${APIAPP_HTTP_PORT:-7100}:8000
    volumes:
      - ${STORAGE_ROOT:-/mnt/share/ai_data}:${APP_STORAGE_ROOT:-/ai_data}:z,rw
    environment:
      DATA_ROOT: ${APP_STORAGE_ROOT:-/ai_data}
      SRC_ROOT: ${APP_SRC_ROOT:-/server}
      ENABLED_PATHS_CONF: ${APP_ENABLED_PATHS:-/app/config/paths.json}
      ENABLED_ROUTES_CONF: ${APP_ENABLED_ROUTES:-/app/config/routes.json}
    command: [ "/usr/local/bin/server-start.sh" ]
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request as u; u.urlopen(\"http://localhost:8000/health\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    networks:
      - ${APP_ENV:-app}-net
