# Local-only override: do not change base compose used for prod/CI
# Frontends are optional via the `frontend` profile; core services always run.

services:
  webapp:
    profiles: ["frontend"]

  siteapp:
    profiles: ["frontend"]

  apiapp:
    build:
      context: .
      dockerfile: apiapp/Dockerfile
    environment:
      SRC_ROOT: /server
      DATA_ROOT: /ai_data
    volumes:
      - ./apiapp/server:/server:rw
      - ./ai_data:/ai_data:rw
      - ./artifacts:/artifacts:rw
      - ./apiapp/init-app/server-start.sh:/usr/local/bin/server-start.sh:ro
    ports:
      - "${APIAPP_HTTP_PORT:-18080}:8000"

  keycloak:
    build:
      context: ./keycloak

  mkdocs:
    build:
      context: ./mkdocs
